import React, { useState } from 'react';
import { Search, Sparkles, ChevronRight, MessageCircleQuestion } from 'lucide-react';
import { askScholarAI } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';

const FatawaSection: React.FC = () => {
  const [query, setQuery] = useState('');
  const [aiResponse, setAiResponse] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setAiResponse(null);
    
    // Simulate API delay for UX if Gemini is very fast
    const response = await askScholarAI(query);
    setAiResponse(response);
    setLoading(false);
  };

  const recentFatawa = [
    {
      id: 1,
      category: 'Worship',
      question: 'Is it permissible to combine prayers due to work?',
      summary: 'Combining prayers is generally allowed for specific valid reasons like travel or severe rain, but work schedule adjustments should be prioritized...',
    },
    {
      id: 2,
      category: 'Transactions',
      question: 'Ruling on using credit cards with cashback?',
      summary: 'Using credit cards is permissible provided one pays the full amount before interest accrues. Cashback is considered a gift...',
    },
    {
      id: 3,
      category: 'Family',
      question: 'Rights of neighbors in Islam',
      summary: 'The rights of neighbors are emphasized greatly in the Sunnah, including safety, sharing food, and not causing harm...',
    }
  ];

  return (
    <section id="fatawa" className="py-24 bg-white relative">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 gap-6">
          <div>
            <h2 className="text-primary-800 font-semibold tracking-wide uppercase text-sm mb-2">Dar-ul-Ifta</h2>
            <h3 className="text-3xl md:text-4xl font-bold font-syne text-gray-900">Ask & Learn</h3>
            <p className="mt-4 text-gray-500 max-w-xl">
              Search our database of rulings or ask our AI research assistant for preliminary information based on authentic sources.
            </p>
          </div>
        </div>

        {/* Search & AI Interface */}
        <div className="bg-gray-50 rounded-3xl p-6 md:p-10 border border-gray-100 shadow-sm mb-16">
          <form onSubmit={handleSearch} className="relative max-w-3xl mx-auto">
            <div className="relative flex items-center">
              <input
                type="text"
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask a question about Salah, Zakat, Fasting..."
                className="w-full pl-6 pr-32 py-5 rounded-2xl border border-gray-200 focus:border-primary-500 focus:ring-4 focus:ring-primary-100 outline-none text-lg transition-all shadow-sm"
              />
              <div className="absolute right-2 flex items-center gap-2">
                <button 
                  type="submit" 
                  disabled={loading}
                  className="bg-primary-800 text-white px-6 py-3 rounded-xl font-semibold hover:bg-primary-900 transition-colors flex items-center gap-2 disabled:opacity-70"
                >
                  {loading ? (
                    <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                  ) : (
                    <>
                      <Sparkles size={18} />
                      <span className="hidden sm:inline">Ask AI</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </form>

          {/* AI Response Area */}
          {aiResponse && (
            <div className="max-w-3xl mx-auto mt-8 animate-fade-in">
              <div className="bg-white border border-primary-100 rounded-2xl p-8 shadow-sm relative overflow-hidden">
                <div className="absolute top-0 left-0 w-1 h-full bg-primary-500" />
                <div className="flex items-start gap-4 mb-4">
                  <div className="p-2 bg-primary-50 rounded-lg">
                    <Sparkles className="text-primary-600" size={20} />
                  </div>
                  <div>
                    <h4 className="font-syne font-bold text-gray-900 text-lg">AI Assistant Response</h4>
                    <p className="text-xs text-gray-400 mt-1">Generated by AI • Consult a scholar for personal rulings</p>
                  </div>
                </div>
                <div className="prose prose-sm prose-emerald text-gray-600 font-manrope leading-relaxed">
                  <ReactMarkdown>{aiResponse}</ReactMarkdown>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Recent Fatawa Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {recentFatawa.map((item) => (
            <div key={item.id} className="group bg-white rounded-2xl border border-gray-100 p-8 hover:shadow-xl hover:shadow-gray-200/50 transition-all duration-300 hover:-translate-y-1">
              <div className="inline-block px-3 py-1 rounded-full bg-accent-50 text-accent-700 text-xs font-bold uppercase tracking-wider mb-4">
                {item.category}
              </div>
              <h4 className="text-xl font-bold font-syne text-gray-900 mb-3 group-hover:text-primary-800 transition-colors">
                {item.question}
              </h4>
              <p className="text-gray-500 text-sm leading-relaxed mb-6 line-clamp-3">
                {item.summary}
              </p>
              <a href="#" className="inline-flex items-center text-primary-700 font-semibold text-sm hover:gap-2 transition-all">
                Read Full Ruling <ChevronRight size={16} className="ml-1" />
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FatawaSection;